package com.example.objectbox.entities;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.relation.ToOne;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;

@Entity
public class Order {

    @Id
    Long id;

    String orderText;

    ToOne<Customer> customer = new ToOne<>(this, Order_.customer);

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Generated(1765253492)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Order(Long id, String orderText, long customerId) {
        this.id = id;
        this.orderText = orderText;
        this.customer.setTargetId(customerId);
    }

    @Generated(1105174599)
    public Order() {
    }

}
